name = "cloudflare-docker-proxy"
workers_dev = true
main = "src/index.js"
compatibility_date = "2021-12-07"
routes = [
    { pattern = "docker.wangminan.me", custom_domain = true },
    { pattern = "quay.wangminan.me", custom_domain = true },
    { pattern = "gcr.wangminan.me", custom_domain = true },
    { pattern = "k8s-gcr.wangminan.me", custom_domain = true },
    { pattern = "k8s.wangminan.me", custom_domain = true },
    { pattern = "ghcr.wangminan.me", custom_domain = true },
    { pattern = "cloudsmith.wangminan.me", custom_domain = true },
]

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol="http"
upstream_protocol="https"

[vars]
MODE="production"
TARGET_UPSTREAM=""

[env.dev.vars]
MODE="debug"
TARGET_UPSTREAM="https://registry-1.docker.io"